FROM php:8.2-fpm

RUN apt-get update && apt-get install -y \
    libpq-dev \
    libzip-dev \
    zip unzip \
    nodejs npm \
    iputils-ping \
    git \
    && docker-php-ext-install pdo pdo_mysql pdo_pgsql pgsql

WORKDIR /var/www/html

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

EXPOSE 9000

USER www-data